### ISSUE TITLE
同じTickerが入っている問題について

### ISSUE THREAD

**Issue by vkdlxh** [vkdlxh/CoinCalculator#3]
<img width="406" alt="2018-02-06 11 33 31" src="https://user-images.githubusercontent.com/23257736/35839051-b564c928-0b31-11e8-837d-542aa479e267.png">

@dolfalf
Managerから`start()`が実行すると、
contentのTickersに６個のTickerが入ります。
ですが、Tickers配列の中身は違うMarketの６個のTickerではなくて、
上記の画像みたいに全部同じ`BTC_JYP`のTicker６個が入っています。

その後、値が変更してcontentのTickers配列が更新すると、
`BTC_JYPのTicker６個`＋`他の５個MarketのTicker`が入って
合わせて１１個のTickerが配列に入っています。

<img width="405" alt="2018-02-06 11 40 37" src="https://user-images.githubusercontent.com/23257736/35839229-9f72c574-0b32-11e8-8201-84e52b70da03.png">

**Comment by vkdlxh** [comment]
ちなみにゼウンさんからマネージャーから修正したOptional処理はなくても良くremoveされているのを確認しました。
ただ以前のTickersの中身が全部`BTC_JYP`ですので、一つだけ削除されますので
残り５個の`BTC_JYP`のTickerと新しい６個のTickerたちが配列に入っていると思います。

**Comment by dolfalf** [comment]
修正しました。私のRepoからスースを上書きしてください。

**Comment by vkdlxh** [comment]
ありがとうございます。
